# .air.toml
# Config file for air: https://github.com/cosmtrek/air

# Working directory
root = "."
tmp_dir = "tmp"

[build]
  # Command to build the application
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  # The binary to run
  bin = "./tmp/main"
  # Extensions to watch
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Directories to exclude from watching
  exclude_dir = ["assets", "tmp", "vendor"]
  # Log file for the build
  log = "air_build.log"
  # Delay between rebuilds
  delay = 1000 # ms

[log]
  # Show time in logs
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
